-- liquibase formatted sql

--changeset iaktov:1
CREATE TABLE socks_warehouse
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    color       VARCHAR NOT NULL,
    quantity    INT     NOT NULL,
    cotton_part INT     NOT NULL
);
