-- liquibase formatted sql

--changeset iaktov:1
CREATE TABLE socks_warehouse
(
    id BIGINT generated by default as identity PRIMARY KEY,
    color TEXT NOT NULL,
    cottonPart BIGINT NOT NULL,
    quantity BIGINT NOT NULL
);
